name: CI - production

on:
  release:
    types: [released]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - id: slackify
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ github.event.release.body }}
      - run: |
          echo "${{ steps.slackify.outputs.tag_name }} : ${{github.event.release.name}} : ${{ steps.slackify.outputs.text }}"
